### ISSUE TITLE
nerv dataset download

### ISSUE THREAD

**Issue by XiaoKangW** [JulianKnodt/nerf_atlas#11]
Hi, Great work!

I try to download the nerv dataset, but it's not work.

so how to download this part dataset and your own  dataset of neural_ray_tracing work including "teapot", "buddha", "bunny" and "armadillo"?

Thanks in advance!

**Comment by JulianKnodt** [comment]
@XiaoKangW For the NeRV dataset does it not open a a google drive download link?

**Comment by JulianKnodt** [comment]
If it doesn't work you should reach out to the authors of that paper, I've asked some other people to check and it doesn't work for them either. Unfortunately I don't have the ability to share that drive, and would not be that comfortable sharing someone else's dataset.

**Comment by JulianKnodt** [comment]
We've compiled a new dataset for lighting conditions, please use this one:
https://drive.google.com/drive/folders/1-0oZ8OGNR2WDw0R9gbNzt1LpeMaxF_vM
Let me know if it works or not!

**Comment by JulianKnodt** [comment]
Closing the issue, our new dataset is linked inside of the readme,
and I can't really/am not comfortable with fixing the NeRV issue without their permission.
